### ISSUE TITLE
PHP 7.3 compliant

### ISSUE THREAD

**Issue by nicoren** [magesuite/css-minifier#1]
Hello,
Please,  could you change the following line :  php": "~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0",
to "php": "~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.3.0" 

Thank you

**Comment by krisdante** [comment]
We will remove the php check totaly. For now I merged the PR that was there.

**Comment by nicoren** [comment]
@krisdante : thank you :)

**Comment by nicoren** [comment]
@krisdante : could you tag new release to use it properly with composer ? 

Thank you

Best regards

**Comment by diwipl** [comment]
@nicoren I've tagged newest commit, it is now available trough packagist.

Best Regards
